Knowman/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth import views
# from search.views import PostingFormView



urlpatterns = [
    # Examples:
    # url(r'^$','search.views.index', name='index'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('search.urls')),
    url(r'^search/$', 'search.views.search', name='search'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    # url(r'^search/', include('haystack.urls')),

]

search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'

urlpatterns = [
    #url(r'^$', views.search, name='index'),
    url(r'^case/(\d+)', views.case_details, name='case_details'),
    url(r'^tblinstallbase/$', views.search_tblinstallbase, name='tblinstallbase_search'),
    url(r'^tblinstallbase/(\d+)/$', views.tblescalation_by_case, name='tblescalation_search'),
    url(r'^searching/', 'search.views.searching', name='searching'),
    url(r'^pcomplete/', 'search.views.pcomplete', name='pcomplete'),
    url(r'^posting/', 'search.views.posting', name='posting'),
    url(r'^details/', 'search.views.case_details', name='details'),
]

search/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove 'managed = False' lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from .search import TblinstallbaseIndex, TblescalationIndex
from django.db.models.signals import post_save
from django.dispatch import receiver

class Case(models.Model):
    # null=True means you can save to DB with this field being blank
    # blank=True means the Django form will not require this field
    user = models.ForeignKey(User)
    case_number = models.CharField(max_length=200)
    utid = models.CharField(max_length=200, blank=True, null=True)
    cse = models.CharField(max_length=200)
    entry_date = models.DateField(default=timezone.now)
    target = models.CharField(max_length=200, blank=True, null=True)
    system = models.CharField(max_length=200, blank=True, null=True)
    subsystem = models.CharField(max_length=200, blank=True, null=True)
    fault = models.CharField(max_length=200, blank=True, null=True)
    symptoms = models.CharField(max_length=200, blank=True, null=True)
    case_summary = models.TextField()
    poa = models.TextField()

class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now=True)


class Ltdrawdata(models.Model):
    fiscal_year = models.IntegerField(db_column='Fiscal year', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    fiscal_quarter = models.IntegerField(db_column='Fiscal Quarter')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    fiscal_month = models.IntegerField(db_column='Fiscal Month')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    calendar_year_quarter = models.IntegerField(db_column='Calendar Year Quarter')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    calendar_year_month = models.IntegerField(db_column='Calendar Year Month')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    region = models.CharField(db_column='Region', max_length=20, blank=True, null=True)  # Field name made lowercase.
    case_number = models.IntegerField(db_column='Case Number')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_title = models.CharField(db_column='Case Title', max_length=200)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    customer_name = models.CharField(db_column='Customer Name', max_length=200)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    business_unit = models.CharField(db_column='Business Unit', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    service_unit = models.CharField(db_column='Service Unit', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    customer_roll_up = models.CharField(db_column='Customer Roll Up', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    utid = models.CharField(db_column='UTID', max_length=200)  # Field name made lowercase.
    product_family = models.CharField(db_column='Product Family', max_length=200)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    product_line = models.CharField(db_column='Product Line', max_length=200)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    alias = models.CharField(db_column='Alias', max_length=200, blank=True, null=True)  # Field name made lowercase.
    model = models.CharField(db_column='Model', max_length=200)  # Field name made lowercase.
    case_owner = models.CharField(db_column='Case Owner', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    account_manager = models.CharField(db_column='Account Manager', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    life_stage = models.CharField(db_column='Life Stage', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_type = models.CharField(db_column='Case Type', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    down_hrs = models.CharField(db_column='Down Hrs', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    entitled_hours = models.CharField(db_column='Entitled Hours', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    ltd_reason = models.CharField(db_column='LTD Reason', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    override_reason = models.CharField(db_column='Override Reason', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    ltd_primary_reason_comments = models.CharField(db_column='LTD Primary Reason Comments', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_modified = models.CharField(db_column='Case Modified', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    cse_error_flag = models.CharField(db_column='CSE Error Flag', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_reason = models.CharField(db_column='Escalation Reason', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_level_l1 = models.CharField(db_column='Escalation Level L1', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_l1_hrs = models.CharField(db_column='Escalation L1 Hrs', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_level_l2 = models.CharField(db_column='Escalation Level L2', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_l2_hrs = models.CharField(db_column='Escalation L2 Hrs', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_level_l3 = models.CharField(db_column='Escalation Level L3', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_l3_hrs = models.CharField(db_column='Escalation L3 Hrs', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_level_l4 = models.CharField(db_column='Escalation Level L4', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    escalation_l4_hrs = models.CharField(db_column='Escalation L4 Hrs', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters. Field renamed because it ended with '_'.

    class Meta:

        db_table = 'LTDRawdata'


class Tblcasesummary(models.Model):
    fab_code = models.IntegerField(db_column='Fab_Code')  # Field name made lowercase.
    case_id = models.IntegerField(db_column='Case ID')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_description = models.CharField(db_column='Case Description', max_length=200)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_type = models.CharField(db_column='Case Type', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    utid = models.IntegerField(db_column='UTID')  # Field name made lowercase.
    model_at_case_creation_time = models.CharField(db_column='Model at Case Creation Time', max_length=200)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_creation_date = models.IntegerField(db_column='Case Creation Date', max_length=200)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_classification_level_1 = models.CharField(db_column='Case Classification level 1', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    case_classification_level_2 = models.CharField(db_column='Case Classification level 2', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    tool_life_stg_per_case = models.CharField(db_column='Tool Life Stg per Case', max_length=200, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:

        db_table = 'TBLCASESUMMARY'


class Tblescalation(models.Model):
    user = models.ForeignKey(User)
    entry_date = models.DateField(default=timezone.now)

search/forms.py
from django import forms
from search.models import Post, Tblescalation, Case


class loginForm(forms.Form):
    log = forms.CharField(label='Your Name', max_length=None)


class SignUpForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('post',)

class SuggestionForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    suggestion = forms.CharField(widget=forms.Textarea)


class TblescalationForm(forms.ModelForm):
    class Meta:
        model = Tblescalation
        # exclude = ['user', 'seven_step']
        fields = ('utid','fab_code', 'case_id', 'tse_owner', 'problem_statement', 'case_description', 'system', 'subsystem', 'fault', 'fix_rca', 'rca_detail', 'poa', 'passdown', 'tse_analysis')


class SearchForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ('symptoms', 'utid')

search/views.py
from django.shortcuts import render
from django.db import models
from django.views.generic import TemplateView, View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
import json
from .models import Tblescalation, Case
from .forms import SuggestionForm, TblescalationForm, SearchForm
# from haystack.query import SearchQuerySet
from .forms import SignUpForm, SuggestionForm
from .search import *
# from search.models import Case


@login_required
def pcomplete(request):
    if request.method == 'POST':
        form = TblescalationForm(request.POST)
        if form.is_valid():
            case_item = form.save(commit=False)
            case_item.user = request.user
            case_item.save()
            return render(request, 'interact/post_complete.html', {'saved_case': case_item})
        else:
            return render(request, 'interact/posting.html', {'form': form})

@login_required
def posting(request):
    form = TblescalationForm()
    return render(request, 'interact/posting.html', {'form': form})


# @login_required
# def searching_db(request):
#     if request.method == 'GET':
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             case_item = form.get
#         return render(request, 'interact/searching.html', {'form': form})


@login_required
def searching(request):
    form = SearchForm()
    return render(request, 'interact/searching.html', {'form': form})


# @login_required
# def search_box(request):
#     form = CaseForm()
#     return render(request, 'search_box.html', {'form': form})

@login_required
def search_tblinstallbase(request):
    utid = ""
    context = {}
    render_template = ""
    if request.method == "POST":
        form_value = SearchForm(request.POST)

    if form_value.is_valid():
        utid = form_value.cleaned_data['utid']
        symptoms = form_value.cleaned_data['symptoms']

        if  symptoms and not utid:
            render_template = 'details/tblescalation.html'
            tblescalation_result = search_tblescalation_symptoms(symptoms)
            context = {
                    'symptoms': symptoms, 
                    'tblescalations':tblescalation_result
            }
        elif not symptoms and utid:
            render_template = 'details/tblinstallbase.html'
            tblinstallbase_result = search_tblinstallbase_utid(utid)
            if not tblinstallbase_result:
                tblinstallbase = None
            else:
                tblinstallbase = tblinstallbase_result[0]
            
            tblescalation_result = search_tblescalation_utid(utid)

            context = {
                    'utid': utid, 
                    'tblinstallbase': tblinstallbase, 
                    'tblescalations':tblescalation_result
            }

        elif symptoms and utid:
            render_template = 'details/tblinstallbase.html'
            tblinstallbase_result = search_tblinstallbase_utid(utid)
            if not tblinstallbase_result:
                tblinstallbase = None
            else:
                tblinstallbase = tblinstallbase_result[0]
            
            tblescalation_result = search_tblescalation(utid, symptoms)

            context = {
                    'utid': utid, 
                    'tblinstallbase': tblinstallbase, 
                    'tblescalations':tblescalation_result
            }
        
        else:
            form = SearchForm()
            return render(request, 'interact/searching.html', {'form': form})
    return  render(request, render_template, context)

@login_required
def tblescalation_by_case(request, case_id):
    if request.method == 'POST':
        caseId = request.POST['case_id']

        value = Tblescalation.objects.filter(case_id = caseId)
        value1 = {
            "system": value[0].system,
            "subsystem": value[0].subsystem,
            "fault": value[0].fault,
            "symptoms": value[0].symptoms,
            "fix_rca": value[0].fix_rca,
            "poa": value[0].poa,
            "tse_analysis": value[0].tse_analysis,
            "rca_detail": value[0].rca_detail,
            "passdown": value[0].passdown
        }
        return HttpResponse(json.dumps(value1))
    else: return HttpResponse("No Submit")

@login_required
def search(request):
    count = Tblescalation.objects.all().count()
    context1 = {
    'count': count,
    }
    return render(request, 'base.html', context1)

@login_required
def case_details(request, number):
    queryset = Case.objects.filter(case_number=number)
    # case = Case.objects.all()
    context = {
        "object_list": queryset,
        # 'case': case,
    }
    return render(request, 'details/detail.html', context)


# @login_required
# def search_titles(request):
#     articles = SearchQuerySet().autocomplete(content_auto=request.POST.get('search_text', ''))
#     return render_to_response('search_results.html', {'articles' : articles})

search/templates/interact/post_complete.html
{% extends 'base.html' %}


{% block body %}
<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-2 loginbox">
  <div class="panel panel-info">
     <div class="panel-heading">
         <div class="panel-title">Post to Knowman</div>
    </div>
    <div class="panel-body">
      <h1>Post completed!!</h1>
      <p>Case DB User: {{saved_case.user}}</p>
      <p>Case#: {{saved_case.case_number}}</p>
      <p>Case Fault: {{saved_case.fault}}</p>
   </div>
   </div>
</div>
{% endblock %}

search/templates/interact/posting.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-2 loginbox">
 <div class="panel panel-info">
   <div class="panel-heading">
      <div class="panel-title">Post to Knowman</div>
   </div>
   <div class="container">
      <div style="width:36%">
         <form action="{% url 'pcomplete' %}" method="POST">
         {% csrf_token %}
         {{ form|crispy }}
         <input type="submit" class="btn-basic"/>
         </form>
      </div>
   </div>
 </div>
</div>

{% comment %}
        <button data-toggle="collapse" data-target="#demo">Collapsible</button>

      <div id="demo" class="collapse">
        </div>

{% endcomment %}
{% endblock %}

search/templates/interact/search_results.html
{% extends 'base.html' %}

{% block body %}

{% if articles.count > 0 %}
{% for article in articles %}
   <li><a href="{{ article.object.get_absolute_url }}">{{ article.object.title }}</a></li>
   {% endfor %}

   {% else %}

   <li>None to show!</li>

   {% endif %}

<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-2 loginbox">
 <div class="panel panel-info">
   <div class="panel-heading">
      <div class="panel-title">Post to Knowman</div>
   </div>
   <div class="container">
      <div style="width:36%">

      </div>
   </div>
 </div>
</div>

{% comment %}
        <button data-toggle="collapse" data-target="#demo">Collapsible</button>

      <div id="demo" class="collapse">
        </div>

{% endcomment %}
{% endblock %}

search/templates/interact/searching.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block body %}

<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-2 loginbox">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="panel-title">Search Knowman</div>
        </div>
        <div class="well">
            <form action="{% url 'search.views.search_tblinstallbase' %}" method="POST">
                {% csrf_token %} {{ form|crispy }}
                <input type="submit" value="Search" class="btn-basic" />
                <br/>
            </form>
        </div>
    </div>
</div>

{% endblock %} 
{% comment %}
<form method="post" action="," class="form-horizontal">
    {% csrf_token %}
    <div id="signupalert" style="display:none" class="alert alert-danger">
        <p> Error:</p>
        <span></span>
    </div>
    <div class="form-group">
        <label for="id_symptom" class="col-md-3 control-label">Symptom</label>
        <div class="col-md-6">
            <input id="id_symptom" type="text" class="form-control" name="symptom" placeholder="Low Haze">
        </div>
    </div>
    <div class="form-group">
        <label for="id_statement" class="col-md-3 control-label">Problem Statement</label>
        <div class="col-md-6">
            <input id="id_statement" type="text" class="form-control" name="statement" placeholder="Motion Error">
        </div>
    </div>
    <div class="form-group">
        <label for="id_UTID" class="col-md-3 control-label">UTID</label>
        <div class="col-md-6">
            <input id="id_UTID" type="text" class="form-control" name="UTID" placeholder="UTID">
        </div>
    </div>
    <div class="form-group">
        <label for="id_system" class="col-md-3 control-label">System</label>
        <div class="col-md-6">
            <select class="custom-select">
      <option selected>Select One</option>
      <option value="1">SP1</option>
      <option value="2">SP2</option>
      <option value="3">SP3</option>
      <option value="4">SP5</option>
      <option value="5">SP7</option>
    </select>
        </div>
    </div>
    <div class="form-group">
        <label for="id_subsystem" class="col-md-3 control-label">Subsystem</label>
        <div class="col-md-6">
            <select class="custom-select">
      <option selected>Select One</option>
      <option value="1">BEA</option>
      <option value="2">BSS</option>
      <option value="3">BPS</option>
      <option value="4">Stage</option>
      <option value="5">DAC</option>
      <option value="6">COL</option>
      <option value="7">Software</option>
    </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-5 col-md-9">
            <button id="btn-signup" type="submit" class="btn btn-Info"><i class="icon-hand-right"></i>Search</button>
        </div>
    </div>
</form>
{% endcomment %}